services:
  api:
    container_name: n3uron-librechat-v085-api
    image: n3uron-librechat-v085:local
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - CONFIG_PATH=/app/librechat.yaml
    volumes:
      - type: bind
        source: ./librechat.yaml
        target: /app/librechat.yaml

  mongodb:
    container_name: n3uron-librechat-v085-mongodb

  meilisearch:
    container_name: n3uron-librechat-v085-meilisearch

  vectordb:
    container_name: n3uron-librechat-v085-vectordb

  rag_api:
    container_name: n3uron-librechat-v085-rag
    extra_hosts:
      - "host.docker.internal:host-gateway"
